import { MemoryItem } from './types';
import { processMemoryList } from './utils/mediaProcessor';

export interface DriveItemDef {
  fileName: string;
  fileId: string;
  title: string;
  location: string;
  date: string;
  tags: string[];
  isVideo?: boolean;
  category: 'Pangilatan Core' | 'Videos' | 'Random Moments' | 'Summer & Nature';
  description?: string;
}

export const ALL_DRIVE_ITEMS: DriveItemDef[] = [
  // ==========================================
  // 1. SPECIFIC SETS OF VIDEOS
  // ==========================================
  {
    fileName: 'Pangilatan_Reconciliation_Moment.mp4',
    fileId: '1ax70qLbZOM0ktjUXIf2Hsc3AbWD83WL_',
    title: 'Pangilatan Reconciliation Moment',
    location: 'Pangilatan • Special Video',
    date: 'Pangilatan Special Moment • Video',
    tags: ['Pangilatan', 'Videos', 'Reconciliation', 'Highlight'],
    isVideo: true,
    category: 'Videos',
    description: 'A special, heartfelt reconciliation moment captured at Pangilatan. Preserved as an essential memory video highlight.',
  },
  {
    fileName: 'Flood_Moment_1.mp4',
    fileId: '1t0B57lu98Q3anDBd47IMfiXekfeOPOEJ',
    title: 'Flood Journey - Torrential Flow',
    location: 'Flood Moments • Video 1',
    date: 'Wild Weather Journey • Video',
    tags: ['Flood Moments', 'Videos', 'Adventure', 'Rain'],
    isVideo: true,
    category: 'Videos',
    description: 'Vivid video footage documenting the intense flood waters and raw power of natural elements on the journey.',
  },
  {
    fileName: 'Flood_Moment_2.mp4',
    fileId: '1Ia4E1bQxsPltOIZFz_JFnQXD6W-0OjGT',
    title: 'Flood Journey - Rising Currents',
    location: 'Flood Moments • Video 2',
    date: 'Wild Weather Journey • Video',
    tags: ['Flood Moments', 'Videos', 'Adventure', 'Torrent'],
    isVideo: true,
    category: 'Videos',
    description: 'Second clip documenting navigating through rising flood conditions, highlighting resilience and adventure.',
  },
  {
    fileName: 'Flood_Moment_3.mp4',
    fileId: '1FttW1UtcHqF0H0fbrCly3fBRDZVD4F5t',
    title: 'Flood Journey - Aftermath & Passage',
    location: 'Flood Moments • Video 3',
    date: 'Wild Weather Journey • Video',
    tags: ['Flood Moments', 'Videos', 'Adventure', 'Memories'],
    isVideo: true,
    category: 'Videos',
    description: 'The continuation of the flood adventure journey, capturing the atmosphere, camaraderie, and unique experience.',
  },
  {
    fileName: 'Gullas_Mountain_Hangout_1.mp4',
    fileId: '1qYVjeokub4tqES8a5xWSJP8tUc4S7UpS',
    title: 'Gullas Mountain Heights - Part I',
    location: 'Gullas Mountain • Hangout',
    date: 'Mountain Retreat • Video',
    tags: ['Gullas Mountain', 'Videos', 'Mountain', 'Hangout'],
    isVideo: true,
    category: 'Videos',
    description: 'Video memories from high up on Gullas Mountain enjoying breezy altitudes and panoramic horizons with friends.',
  },
  {
    fileName: 'Gullas_Mountain_Hangout_2.mp4',
    fileId: '1b2acsY_0FGG60gzYedDQlyjmFH1rBTb1',
    title: 'Gullas Mountain Heights - Part II',
    location: 'Gullas Mountain • Hangout',
    date: 'Mountain Retreat • Video',
    tags: ['Gullas Mountain', 'Videos', 'Mountain', 'Hangout'],
    isVideo: true,
    category: 'Videos',
    description: 'Relaxed hangout vibes and scenic mountain viewpoints captured on video at Gullas Mountain.',
  },
  {
    fileName: 'Beach_Hangout.mp4',
    fileId: '1pHq63-BgmAGal8kEkl33kmFSKteWdLNB',
    title: 'Beach Coastal Hangout',
    location: 'Beach Hangout • Video',
    date: 'Coastal Getaway • Video',
    tags: ['Beach Hangout', 'Videos', 'Ocean', 'Waves'],
    isVideo: true,
    category: 'Videos',
    description: 'Golden sunlight, soothing coastal breezes, and fun beach hangout moments captured in full motion.',
  },
  {
    fileName: 'Long_Rides_1.mp4',
    fileId: '1Or8orG13J4pw6-gmoZjDibGDVSCfjclb',
    title: 'Scenic Open Road Ride - Part I',
    location: 'Long Rides • Highway & Trail',
    date: 'Road Odyssey • Video',
    tags: ['Long Rides', 'Videos', 'Riding', 'OpenRoad'],
    isVideo: true,
    category: 'Videos',
    description: 'Cruising through endless open roads and winding scenery on an exhilarating long ride adventure.',
  },
  {
    fileName: 'Long_Rides_2.mp4',
    fileId: '1HSmweBarLFZ92UVT0ECxvOZQH6Nl2nmi',
    title: 'Scenic Open Road Ride - Part II',
    location: 'Long Rides • Highway & Trail',
    date: 'Road Odyssey • Video',
    tags: ['Long Rides', 'Videos', 'Riding', 'Journey'],
    isVideo: true,
    category: 'Videos',
    description: 'The freedom of the journey captured during a breathtaking stretch of scenic highway riding.',
  },

  // ==========================================
  // 2. PANGILATAN CORE FILES
  // ==========================================
  {
    fileName: '20260531_155029.jpg',
    fileId: '16Y45AClQV-QPJFJopdeHItKZjuIiWhyQ',
    title: 'Pangilatan Trail Vista 15:50',
    location: 'Pangilatan Core • May 31',
    date: 'May 31, 2026 • 15:50',
    tags: ['Pangilatan', 'Core', 'Trail', 'May 31'],
    category: 'Pangilatan Core',
    description: 'Core Pangilatan moment captured along the mountain ridges during late afternoon exploration.',
  },
  {
    fileName: '20260531_151821.jpg',
    fileId: '1e9tm3i8Ay1Mtog8BQ9F4gucB08rFCGzz',
    title: 'Pangilatan Natural Flora 15:18',
    location: 'Pangilatan Core • May 31',
    date: 'May 31, 2026 • 15:18',
    tags: ['Pangilatan', 'Core', 'Flora', 'Nature'],
    category: 'Pangilatan Core',
    description: 'Rich greenery and lush flora framing the serene landscapes of Pangilatan.',
  },
  {
    fileName: '20260531_151736.jpg',
    fileId: '1smj64ajtPckAIyyWY5oqHY8RkzgKl7pB',
    title: 'Pangilatan Forest Sanctuary 15:17',
    location: 'Pangilatan Core • May 31',
    date: 'May 31, 2026 • 15:17',
    tags: ['Pangilatan', 'Core', 'Forest', 'Sanctuary'],
    category: 'Pangilatan Core',
    description: 'Quiet sunlight piercing through the peaceful natural groves of Pangilatan.',
  },
  {
    fileName: '20260531_151529.jpg',
    fileId: '10Vv9RMxrD42ZHfnfC5xvw7o-34IXNcb_',
    title: 'Pangilatan Pathway 15:15',
    location: 'Pangilatan Core • May 31',
    date: 'May 31, 2026 • 15:15',
    tags: ['Pangilatan', 'Core', 'Pathway', 'Discovery'],
    category: 'Pangilatan Core',
    description: 'Walking the pristine trails of Pangilatan surrounded by fresh mountain air.',
  },

  // ==========================================
  // 3. RANDOM FOLDER FILES
  // ==========================================
  {
    fileName: 'IMG_20251127_173543_265.jpg',
    fileId: '1VepSI-NLip_Db2N0jEfD2NXfmlx3HJ-v',
    title: 'November Twilight Atmosphere',
    location: 'Random Moments • Nov 27',
    date: 'Nov 27, 2025 • 17:35',
    tags: ['Random Moments', 'Autumn', 'Twilight', 'Atmosphere'],
    category: 'Random Moments',
    description: 'Dusk settling gently across the surroundings in late November.',
  },
  {
    fileName: 'IMG_20251020_162226_822.jpg',
    fileId: '1_SxoGSwgKXHnEghGlFVG4NxoH2Ermgue',
    title: 'October Afternoon Radiance',
    location: 'Random Moments • Oct 20',
    date: 'Oct 20, 2025 • 16:22',
    tags: ['Random Moments', 'October', 'Sunlight', 'Snapshot'],
    category: 'Random Moments',
    description: 'Warm October afternoon sun casting golden tones across the scene.',
  },
  {
    fileName: '20260704_054251.jpg',
    fileId: '1FUhX2lJkqllKKNmr_thz18c4Uz_5DQgQ',
    title: 'July 4th Dawn Awakening 05:42',
    location: 'Random Moments • July 4',
    date: 'July 4, 2026 • 05:42',
    tags: ['Random Moments', 'July 4', 'Sunrise', 'Summer'],
    category: 'Random Moments',
    description: 'Crisp morning daylight breaking over the landscape on the Fourth of July.',
  },
  {
    fileName: '20260722_171913.jpg',
    fileId: '1NFvjCnB-JQut88nD7gKe5tdyvMcYXbY3',
    title: 'Summer Evening Glow 17:19',
    location: 'Random Moments • July 22',
    date: 'July 22, 2026 • 17:19',
    tags: ['Random Moments', 'July 22', 'Sunset', 'Glow'],
    category: 'Random Moments',
    description: 'Vibrant golden hour glow coloring the horizon in late July.',
  },
  {
    fileName: '20260714_160548.jpg',
    fileId: '1f3oBBoyh3T63C9W8iUw8U4iK3-cMKfbu',
    title: 'Mid-July Exploration 16:05',
    location: 'Random Moments • July 14',
    date: 'July 14, 2026 • 16:05',
    tags: ['Random Moments', 'July 14', 'Outdoor', 'Adventure'],
    category: 'Random Moments',
    description: 'Capturing unique local landmarks and details during mid-July travels.',
  },
  {
    fileName: '20260714_160538.jpg',
    fileId: '1Bbekg6FM5PyNt_-1aCJ2J_Ph5KSUGgin',
    title: 'Scenic Focus 16:05',
    location: 'Random Moments • July 14',
    date: 'July 14, 2026 • 16:05',
    tags: ['Random Moments', 'July 14', 'Travel', 'Perspective'],
    category: 'Random Moments',
    description: 'Artfully framed vantage point during an afternoon excursion.',
  },
  {
    fileName: '20260630_185604.jpg',
    fileId: '1JmMjKGKaktlpIlEtxIpNcT0TxzbMO1mY',
    title: 'June Twilight Horizon 18:56',
    location: 'Random Moments • June 30',
    date: 'June 30, 2026 • 18:56',
    tags: ['Random Moments', 'June', 'Dusk', 'Summer'],
    category: 'Random Moments',
    description: 'End of June twilight skies presenting rich shades of indigo and amber.',
  },
  {
    fileName: '20260630_185606.jpg',
    fileId: '1J0ZDRpVRMs5pXI059HO8YWgHoLMV3X2H',
    title: 'Midsummer Silhouette 18:56',
    location: 'Random Moments • June 30',
    date: 'June 30, 2026 • 18:56',
    tags: ['Random Moments', 'June', 'Silhouette', 'Atmosphere'],
    category: 'Random Moments',
    description: 'Delicate silhouettes outlined against the luminous midsummer evening.',
  },
  {
    fileName: '20260704_054343.jpg',
    fileId: '1EE1sh-n9RrGUxJNvpq7dGsxm8c9z63qU',
    title: 'Sunrise Horizon Colors 05:43',
    location: 'Random Moments • July 4',
    date: 'July 4, 2026 • 05:43',
    tags: ['Random Moments', 'July 4', 'Sunrise', 'Colors'],
    category: 'Random Moments',
    description: 'Panoramic sunrise colors greeting early morning travelers on July 4th.',
  },
  {
    fileName: '20260704_054749.jpg',
    fileId: '1KxzztsYsjpsvIETV7r0AcC4NVUc41wSh',
    title: 'Morning Sun Reflections 05:47',
    location: 'Random Moments • July 4',
    date: 'July 4, 2026 • 05:47',
    tags: ['Random Moments', 'July 4', 'Reflections', 'Dawn'],
    category: 'Random Moments',
    description: 'Golden reflections bouncing across terrain as the sun ascends.',
  },
  {
    fileName: '20260531_151738.jpg',
    fileId: '1Qq8ZqOf7ieUcUV5IbWlWfAmq_ZrqREeo',
    title: 'Verdant Forest Canopy 15:17',
    location: 'Random Moments • May 31',
    date: 'May 31, 2026 • 15:17',
    tags: ['Random Moments', 'May 31', 'Greenery', 'Nature'],
    category: 'Random Moments',
    description: 'Intricate branches and dense canopy providing comforting shade.',
  },
  {
    fileName: '20260531_151455.jpg',
    fileId: '1QXFiSfD250FH884k_NTwqFDwM7YfFCGc',
    title: 'Spring Day Trailhead 15:14',
    location: 'Random Moments • May 31',
    date: 'May 31, 2026 • 15:14',
    tags: ['Random Moments', 'May 31', 'Trailhead', 'Spring'],
    category: 'Random Moments',
    description: 'Stepping onto the winding trail under clear blue skies in May.',
  },
  {
    fileName: '20260531_151523.jpg',
    fileId: '1Nm80b5sDfycKBYtEuELpNkBgSCqkWat3',
    title: 'Sun-Dappled Path 15:15',
    location: 'Random Moments • May 31',
    date: 'May 31, 2026 • 15:15',
    tags: ['Random Moments', 'May 31', 'Sunlight', 'Path'],
    category: 'Random Moments',
    description: 'Sunlight filtering through foliage, creating patterns along the gravel road.',
  },
  {
    fileName: '20260531_151459.jpg',
    fileId: '1eSZssJ3-Jt4u8ziZv6nZOh_DxXC3HMzs',
    title: 'Quiet Meadow Haven 15:14',
    location: 'Random Moments • May 31',
    date: 'May 31, 2026 • 15:14',
    tags: ['Random Moments', 'May 31', 'Meadow', 'Peace'],
    category: 'Random Moments',
    description: 'Peaceful pause near open grassland surrounded by native flora.',
  },
  {
    fileName: 'IMG_20251020_174542_546.jpg',
    fileId: '1HZhN-iKpxp20s5hqvaA-aHyUvNyG88eJ',
    title: 'Late October Twilight',
    location: 'Random Moments • Oct 20',
    date: 'Oct 20, 2025 • 17:45',
    tags: ['Random Moments', 'October', 'Dusk', 'Vibes'],
    category: 'Random Moments',
    description: 'Crisp evening shadows stretching out as twilight falls in autumn.',
  },

  // ==========================================
  // 4. SUMMER & NATURE COLLECTION
  // ==========================================
  {
    fileName: '20260722_145535.jpg',
    fileId: '1j-vL5pZBTYN_p70BpyOngm5vBt6X7ubK',
    title: 'Captured Moment 14:55',
    location: 'Summer & Nature • July 22',
    date: 'July 22, 2026 • 14:55',
    tags: ['Summer', 'July 22', 'Outdoor', 'Memory'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260704_045214.jpg',
    fileId: '15PY1oiQOZCsj_ji0NlC17FYEZ9Wvy_27',
    title: 'Early Dawn Vista 04:52',
    location: 'Summer & Nature • July 4',
    date: 'July 4, 2026 • 04:52',
    tags: ['Sunrise', 'July 4', 'EarlyMorning', 'Landscape'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260704_051343.jpg',
    fileId: '1X5cMyg6WT98KBhTCY457gE71Oo8-eie0',
    title: 'Golden Horizon 05:13',
    location: 'Summer & Nature • July 4',
    date: 'July 4, 2026 • 05:13',
    tags: ['GoldenHour', 'July 4', 'Sky', 'Memory'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260704_073647.jpg',
    fileId: '12NLS_xlPseWd-bpblm6aEomfKobEX8b',
    title: 'Morning Light 07:36',
    location: 'Summer & Nature • July 4',
    date: 'July 4, 2026 • 07:36',
    tags: ['Morning', 'July 4', 'Sunshine', 'Scenic'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260714_162634.jpg',
    fileId: '1xyl63DYn8Jcc0-Ws723nkcEwxulgVJFF',
    title: 'Afternoon Panorama 16:26',
    location: 'Summer & Nature • July 14',
    date: 'July 14, 2026 • 16:26',
    tags: ['Afternoon', 'July 14', 'Travel', 'Explore'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260714_162641.jpg',
    fileId: '1htHOS8VrZesd5pfALYWW2sZmj4qpG766',
    title: 'Scenic Perspective 16:26',
    location: 'Summer & Nature • July 14',
    date: 'July 14, 2026 • 16:26',
    tags: ['Afternoon', 'July 14', 'Vibe', 'Framed'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260722_150949.jpg',
    fileId: '1UdJgaGOlRzyw3oRccvOs3xy3dCSCJY8M',
    title: 'Summer Walk 15:09',
    location: 'Summer & Nature • July 22',
    date: 'July 22, 2026 • 15:09',
    tags: ['Summer', 'July 22', 'Walk', 'Sunny'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260722_161638.jpg',
    fileId: '1evp1loYdYpkGcW5hZ4OnvqbdminXJQdr',
    title: 'Late Afternoon Light 16:16',
    location: 'Summer & Nature • July 22',
    date: 'July 22, 2026 • 16:16',
    tags: ['Summer', 'July 22', 'Afternoon', 'Moment'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_151526.jpg',
    fileId: '17OZuhFtTgWzZ7ISpXgiMbEEb-G4Fygfo',
    title: 'May Journey 15:15',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:15',
    tags: ['Spring', 'May 31', 'Adventure', 'Snapshot'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_151926.jpg',
    fileId: '1aKH4a8_k4BNH0S4936RhHiBJOBDnZMmH',
    title: 'Quiet Path 15:19',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:19',
    tags: ['Nature', 'May 31', 'Spring', 'Trail'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_151947.jpg',
    fileId: '1Vb7v67Cg_MKikNX6El5nUZs-95d4T1oW',
    title: 'Greenery & Skies 15:19',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:19',
    tags: ['Green', 'May 31', 'Spring', 'Atmosphere'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_151955.jpg',
    fileId: '1Na4jOwBrd-HCZnG7jhvSEbkdJhFLvR-V',
    title: 'Spring Day Vista 15:19',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:19',
    tags: ['Spring', 'May 31', 'Sunlight', 'Memory'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_151957.jpg',
    fileId: '1WldaWhFgxMr-I0TxT2xVud5EXWo2O3zj',
    title: 'Scenic Flora 15:19',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:19',
    tags: ['Flora', 'May 31', 'Nature', 'Detail'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_151958.jpg',
    fileId: '1Z3VMARReDgzz2kEiA71QKjRVZyn40XuO',
    title: 'Passing Moment 15:19',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:19',
    tags: ['Snapshot', 'May 31', 'Memories', 'Outdoors'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_152145.jpg',
    fileId: '1M5qGMXG9pvYyFlWAWPz9KN9jU2urfvPt',
    title: 'Open Horizons 15:21',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:21',
    tags: ['Horizon', 'May 31', 'ClearSky', 'Wanderlust'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_152200.jpg',
    fileId: '1XP7og3glznBO3moDbrLpVdORF5EHXWoD',
    title: 'Calm Surroundings 15:22',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:22',
    tags: ['Calm', 'May 31', 'Serenity', 'Travel'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_153828.jpg',
    fileId: '1N38QNAYpo0ueFjC0iYm87HH_YMBNCIj2',
    title: 'Afternoon Discovery 15:38',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:38',
    tags: ['Discovery', 'May 31', 'Afternoon', 'Scenic'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_153831.jpg',
    fileId: '1sQWYDLQrLAuixAsneUONvJyu7RhhBwIg',
    title: 'Wandering Angle 15:38',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:38',
    tags: ['Perspective', 'May 31', 'Exploration', 'Memory'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_153843.jpg',
    fileId: '1xtGRFVmHwx-mM3DphaDw_3Pvg708tnRE',
    title: 'Vivid Landscape 15:38',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:38',
    tags: ['Landscape', 'May 31', 'Vivid', 'Outdoors'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_154019.jpg',
    fileId: '1xpHA_mF2N5mhXae0T3FXlI6p2oTFir46',
    title: 'Sunlit Reflections 15:40',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:40',
    tags: ['Sunlight', 'May 31', 'Reflections', 'Warmth'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_154025.jpg',
    fileId: '1KVoUvIVNBONYIXqHgb_5elq2P5y-br7i',
    title: 'Serene Scenery 15:40',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:40',
    tags: ['Serenity', 'May 31', 'Scenery', 'Memory'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_154133.jpg',
    fileId: '1UCk5VEDNkVplKFMS5ENkjjTQU5PiDAye',
    title: 'Trailside Vista 15:41',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:41',
    tags: ['Trail', 'May 31', 'Vista', 'Outdoor'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_154137.jpg',
    fileId: '1p8_i78s0qiVcNFYsYl-4USR_QZwL6n6z',
    title: 'Gentle Breezes 15:41',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:41',
    tags: ['Breeze', 'May 31', 'Calm', 'Nature'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_154141.jpg',
    fileId: '1Q2R8q1_2L-ZUcG4DSh_ycsqT-0K3n8pH',
    title: 'May Atmosphere 15:41',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:41',
    tags: ['Atmosphere', 'May 31', 'Peace', 'Memory'],
    category: 'Summer & Nature',
  },
  {
    fileName: '20260531_154146.jpg',
    fileId: '1BrIMF2OxYMHHcW0_trgUwWvQffWHAWqv',
    title: 'Golden Day Departure 15:41',
    location: 'Summer & Nature • May 31',
    date: 'May 31, 2026 • 15:41',
    tags: ['Departure', 'May 31', 'GoldenHour', 'Memories'],
    category: 'Summer & Nature',
  },
];

export const HARDCODED_MEMORIES: MemoryItem[] = processMemoryList(
  ALL_DRIVE_ITEMS.map((p) => ({
    id: `drive-${p.fileId}`,
    driveFileId: p.fileId,
    name: p.fileName,
    title: p.title,
    location: p.location,
    date: p.date,
    imageUrl: `https://lh3.googleusercontent.com/d/${p.fileId}=s1200`,
    thumbnailUrl: `https://lh3.googleusercontent.com/d/${p.fileId}=s800`,
    webViewLink: `https://drive.google.com/file/d/${p.fileId}/view?usp=drive_web`,
    videoEmbedUrl: p.isVideo ? `https://drive.google.com/file/d/${p.fileId}/preview` : undefined,
    videoUrl: p.isVideo ? `https://lh3.googleusercontent.com/d/${p.fileId}=s1200` : undefined,
    isVideo: p.isVideo || false,
    category: p.category,
    description: p.description || `Cherished memory "${p.title}" preserved in the 3D memory sphere gallery walk.`,
    tags: p.tags,
    mimeType: p.isVideo ? 'video/mp4' : 'image/jpeg',
  }))
);
